version: '3'

dotenv: ['.env']

vars:
  MIGRATE_VERSION: v4.19.1

tasks:
  default:
    cmds:
      - task --list
    silent: true

  db:up:
    desc: "Menjalankan PostgreSQL dan NocoDB di background"
    cmds:
      - |
        if command -v podman-compose >/dev/null 2>&1; then
          podman-compose up -d
        else
          docker compose up -d
        fi

  db:down:
    desc: "Mematikan PostgreSQL dan NocoDB"
    cmds:
      - |
        if command -v podman-compose >/dev/null 2>&1; then
          podman-compose down
        else
          docker compose down
        fi

  migrate:create:
    desc: "Membuat file migrasi baru. Penggunaan: task migrate:create -- <nama_tabel>"
    cmds:
      - go run github.com/golang-migrate/migrate/v4/cmd/migrate@{{.MIGRATE_VERSION}} create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}

  migrate:up:
    desc: "Menjalankan migrasi database ke versi terbaru"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@{{.MIGRATE_VERSION}} -path db/migrations -database "{{.DATABASE_URL}}" up

  migrate:down:
    desc: "Mengembalikan (rollback) migrasi database 1 langkah"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@{{.MIGRATE_VERSION}} -path db/migrations -database "{{.DATABASE_URL}}" down 1

  sqlc:generate:
    desc: "Meng-generate ulang kode Go dari file SQL menggunakan SQLC"
    cmds:
      - go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0 generate

  dev:
    desc: "Menjalankan aplikasi Go (Contoh)"
    cmds:
      - go run .
